### ISSUE TITLE
loading remote context failed: http://purl.bdrc.io/context.jsonld

### ISSUE THREAD

**Issue by xristy** [buda-base/git-to-dbs#5]
Updated to the latest and ran:

     time java -jar target/fusekicouchdb-0.7.jar -transferAllDB -doNotListen -timeout 30 -progress

It appears that JsonLDReader is trying to GET:

     http://purl.bdrc.io/context.jsonld

and failing with the following on all docs:

> $ time java -jar target/fusekicouchdb-0.7.jar -transferAllDB -doNotListen -timeout 30 -progress
[main] INFO fuseki-couchdb - connecting to couchdb on http://localhost:13598
[main] INFO fuseki-couchdb - connecting to fuseki on http://localhost:13180/fuseki/bdrcrw/data
[main] INFO fuseki-couchdb - Transferring 249 docs to Fuseki
[main] ERROR org.apache.jena.riot - loading remote context failed: http://purl.bdrc.io/context.jsonld
[main] ERROR fuseki-couchdb - Error transfering bdr:C1
org.apache.jena.riot.RiotException: loading remote context failed: http://purl.bdrc.io/context.jsonld
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:137)
	at org.apache.jena.riot.lang.JsonLDReader.read$(JsonLDReader.java:162)
	at org.apache.jena.riot.lang.JsonLDReader.read(JsonLDReader.java:101)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:298)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:288)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:237)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:417)
	at io.bdrc.fusekicouchdb.TransferHelpers.addDocIdInModel(TransferHelpers.java:255)
	at io.bdrc.fusekicouchdb.TransferHelpers.transferOneDoc(TransferHelpers.java:188)
	at io.bdrc.fusekicouchdb.TransferHelpers.transferCompleteDB(TransferHelpers.java:159)
	at io.bdrc.fusekicouchdb.TransferHelpers.transferAllDBs(TransferHelpers.java:133)
	at io.bdrc.fusekicouchdb.FusekiTransfer.main(FusekiTransfer.java:134)
[main] ERROR org.apache.jena.riot - loading remote context failed: http://purl.bdrc.io/context.jsonld
[main] ERROR fuseki-couchdb - Error transfering bdr:C10
org.apache.jena.riot.RiotException: loading remote context failed: http://purl.bdrc.io/context.jsonld
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:137)
	at org.apache.jena.riot.lang.JsonLDReader.read$(JsonLDReader.java:162)
	at org.apache.jena.riot.lang.JsonLDReader.read(JsonLDReader.java:101)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:298)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:288)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:237)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:417)
	at io.bdrc.fusekicouchdb.TransferHelpers.addDocIdInModel(TransferHelpers.java:255)
	at io.bdrc.fusekicouchdb.TransferHelpers.transferOneDoc(TransferHelpers.java:188)
	at io.bdrc.fusekicouchdb.TransferHelpers.transferCompleteDB(TransferHelpers.java:159)
	at io.bdrc.fusekicouchdb.TransferHelpers.transferAllDBs(TransferHelpers.java:133)
	at io.bdrc.fusekicouchdb.FusekiTransfer.main(FusekiTransfer.java:134)
[main] ERROR org.apache.jena.riot - loading remote context failed: http://purl.bdrc.io/context.jsonld

**Comment by eroux** [comment]
can you check if [jarcache.json](https://github.com/BuddhistDigitalResourceCenter/fuseki-couchdb/blob/master/src/main/resources/jarcache.json) is in the .jar? That's where the magic is supposed to happen...

**Comment by xristy** [comment]
[`jarcache.json`](https://github.com/BuddhistDigitalResourceCenter/fuseki-couchdb/blob/master/src/main/resources/jarcache.json) is indeed in the jar with the content:

    [
      {
        "Content-Location": "http://purl.bdrc.io/context.jsonld",
        "X-Classpath": "owl-schema/context.jsonld",
        "Content-Type": "application/ld+json"
      }
    ]

but the owl-schema/context.jsonld wasn't present owing to needing to do:

     git submodule update --init

after that it is now working.

Sorry for bugging you
